#!/bin/bash

# Usage: ./copy [workshop number (from)] [branch name (from)] [workshop number (to)] [branch name (to)]
# Copies the last commit from the source workshop/branch to the target workshop/branch

set -e
cd catbook-workshop$1
git checkout $2

COMMIT=$(git rev-parse HEAD)

# copying commits across repos
if [ $1 != $3 ]; then
    cd ../catbook-workshop$3
    git fetch workshop$1
fi

git checkout $4
git cherry-pick $COMMIT
echo "Applied commit"
